"""Add email and avatar_url to User

Revision ID: 3ea1ad89760b
Revises: 75a4429d69ee
Create Date: 2024-05-14 01:04:53.700620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea1ad89760b'
down_revision = '75a4429d69ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.drop_column('userInfo')
        batch_op.drop_column('avatar_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('userInfo', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
