"""Add email and avatar_url to User

Revision ID: 75a4429d69ee
Revises: c3f849b0f418
Create Date: 2024-05-14 00:57:57.612527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a4429d69ee'
down_revision = 'c3f849b0f418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('userInfo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('userInfo')
        batch_op.drop_column('avatar_path')

    # ### end Alembic commands ###
